[project]
name = "proyecto-i"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "focab0r", email = "focab0r@proton.me" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
    "requests>=2.34.2",
]

[project.scripts]
proyecto-i = "proyecto_i:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
